openapi: 3.0.3
info:
  title: Services API
  description: API for managing and discovering services within an organization.
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /services:
    get:
      summary: List services
      description: Retrieve a paginated list of services with optional filtering.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          required: false
          description: Page number for pagination (default 1).
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 100
          required: false
          description: Number of items per page (default 10).
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Filter services by name.
      responses:
        "200":
          description: List of services
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListServicesResponse'

  /services/{service_id}:
    get:
      summary: Get service by ID
      description: Retrieve details of a specific service.
      parameters:
        - in: path
          name: service_id
          schema:
            type: string
          required: true
          description: ID of the service.
      responses:
        "200":
          description: Service details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetServiceResponse'
        "404":
          description: Service not found

  /services/{service_id}/versions:
    get:
      summary: List versions of a service
      description: Retrieve all versions available for a given service.
      parameters:
        - in: path
          name: service_id
          schema:
            type: string
          required: true
          description: ID of the service.
      responses:
        "200":
          description: List of service versions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListServiceVersionsByServiceIDResponse'
        "404":
          description: Service not found

components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ListServicesResponse:
      type: object
      properties:
        total:
          type: integer
        size:
          type: integer
        page:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/Service'

    GetServiceResponse:
      allOf:
        - $ref: '#/components/schemas/Service'

    ServiceVersion:
      type: object
      properties:
        service_id:
          type: string
        version_id:
          type: string
        created_at:
          type: string
          format: date-time
        is_active:
          type: boolean

    ListServiceVersionsByServiceIDResponse:
      type: object
      properties:
        total:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/ServiceVersion'
