// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ikshavaku/catalogue/api"
	service2 "github.com/ikshavaku/catalogue/api/service"
	"github.com/ikshavaku/catalogue/service"
	"github.com/ikshavaku/catalogue/store/postgres"
	"github.com/ikshavaku/catalogue/store/postgres/repositories"
)

// Injectors from wire.go:

func InjectServicesController() api.IServiceAPIController {
	postgresConfig := postgres.ProvidePostgresConfig()
	postgresURL := postgres.ProvidePostgresURL(postgresConfig)
	pool := postgres.ProvidePostgresConnection(postgresURL)
	queries := postgres.ProvidePostgresQueries(pool)
	serivcesRepository := repositories.ProvideServicesRepository(queries)
	servicesService := service.ProvideServicesService(serivcesRepository)
	serviceAPIController := service2.ProvideServiceAPIController(servicesService)
	return serviceAPIController
}
