// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Service struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	IsDeleted   bool
}

type ServiceVersion struct {
	ServiceID     int32
	VersionNumber string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	IsDeleted     bool
}
